# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDWebImageEncrypt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDWebImageEncrypt
  # SDWebImage 5.x
#  pod 'SDWebImage', '~> 5.0'
#  pod 'SDWebImageWebPCoder'
  # SDWebImage 4.x
  pod 'SDWebImage', '~> 4.4.8'
  pod 'SDWebImage/WebP'
  pod 'SDWebImage/GIF'

  target 'SDWebImageEncryptTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDWebImageEncryptUITests' do
    # Pods for testing
  end

end
